const data = {
  products: [
    {
      _id: "1",
      name: "Redwolf Branded Hoodie",
      category: "Hoodie",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Redwolf",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Redwolf T-shirt",
      category: "T-shirt",
      image: "/images/p2.jpg",
      price: 125,
      countInStock: 20,
      brand: "Redwolf",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Redwolf Jacket",
      category: "Jacket",
      image: "/images/p3.jpg",
      price: 130,
      countInStock: 0,
      brand: "Redwolf",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Redwolf Full Sleeve T-Shirt",
      category: "Full Sleeve T-Shirt",
      image: "/images/p4.jpg",
      price: 150,
      countInStock: 15,
      brand: "Redwolf",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Redwolf Polo T-Shirt",
      category: "Polo T-Shirt",
      image: "/images/p5.jpg",
      price: 155,
      countInStock: 5,
      brand: "Redwolf",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Redwolf Sleeveless T-Shirt",
      category: "Hoodie",
      image: "/images/p6.jpg",
      price: 200,
      countInStock: 12,
      brand: "Redwolf",
      rating: 4.2,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
